### ISSUE TITLE
Lots of flickering under Wayland on Nvidia

### ISSUE THREAD

**Issue by ralmond** [Alex313031/thorium#446]
**System Details**
 - OS: Pop_OS 22.04, Gnome 42.9, Nvidia drivers 545.29.02
 - Thorium Version 117.0.5938.157 

**Problem**
I am experiencing a lot of flickering (often windows behind the browser momentarily popping up over the browser window).  This especially happens when watching videos on YouTube, although it occassionally happens elsewhere, particularly when popping up dialogs (e.g., saving a file).  Also, dropdown menus initially appear blank, but if I move the mouse down over them, the menu text appears.

These issues are not occurring with  Chromium 119.0.6045.159,

**Additional Notes**
The problem seems to have gotten noticeably worse since upgrading my nvidia drivers to 29.02.  This may be a weird interaction between Thorium, Wayland/Gnome and the Nvidia driver.

**Comment by sleeplessKomodo** [comment]
```
System:
  Host: nobara Kernel: 6.5.9-201.fsync.fc38.x86_64 arch: x86_64 bits: 64
    compiler: gcc v: 2.39-15.fc38 Desktop: KDE Plasma v: 5.27.9 tk: Qt
    v: 5.15.11 wm: kwin_wayland dm: SDDM Distro: Nobara release 38 (Thirty
    Eight) base: RHEL 38
    Graphics:
  Device-1: NVIDIA TU104 [GeForce RTX 2080 SUPER] vendor: eVga.com.
    driver: nvidia v: 535.113.01 arch: Turing pcie: speed: 8 GT/s lanes: 16
    ports: active: none off: DP-2,HDMI-A-1 empty: DP-1,DP-3,Unknown-1
    bus-ID: 08:00.0 chip-ID: 10de:1e81
```

Similar issues on Fedora (Nobara) 38.
